apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-api-dev

resources:
- ../../base/
- ./infra/
- ./resources/tier-mapping-configmap.yaml
- ../../policies

namespace: maas-api

transformers:
- transformers/namespace.yaml

patches:
- path: patches/debug-mode.yaml

images:
- name: maas-api
  newName: quay.io/opendatahub/maas-api
  newTag: latest
