apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-api-dev

resources:
- ../../../../deployment/base/maas-api

patches:
- path: patches/debug-mode.yaml

images:
- name: maas-api
  newName: quay.io/opendatahub/maas-api
  newTag: latest
