apiVersion: apps/v1
kind: Deployment
metadata:
  name: maas-api
spec:
  template:
    spec:
      containers:
      - name: maas-api
        env:
        - name: ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: maas-api-admin-secret
              key: admin-api-key
