apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-observability
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: llm-observability

resources:
  - grafana-instance.yaml
  - route.yaml