- op: replace
  path: /metadata/name
  value: payload-pre-processing
- op: replace
  path: /spec/selector/matchLabels/app
  value: payload-pre-processing
- op: replace
  path: /spec/template/metadata/labels/app
  value: payload-pre-processing
- op: replace
  path: /spec/template/spec/containers/0/name
  value: payload-pre-processing
- op: replace
  path: /spec/template/spec/containers/0/args
  value:
  - --config-file
  - "/config/custom-pre-processing-ipp-config.yaml"
  - --v=3
  - --tracing=false
- op: replace
  path: /spec/template/spec/containers/0/ports
  value:
    - containerPort: 9004
      name: grpc
      protocol: TCP
- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"
