ARG BUILDPLATFORM
ARG TARGETPLATFORM

FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi9/go-toolset@sha256:8cf89835994846ca0dffb9078e3a5638c57ec6175750f0af02fbe9c9942696d3 AS builder
ARG CGO_ENABLED=1
ARG GOEXPERIMENT=strictfipsruntime
ARG TARGETOS
ARG TARGETARCH

WORKDIR /app
COPY maas-controller/go.mod maas-controller/go.sum ./
RUN go mod download
COPY maas-controller/ ./

USER root
RUN CGO_ENABLED=${CGO_ENABLED} GOEXPERIMENT=${GOEXPERIMENT} GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} go build -a -trimpath -ldflags="-s -w" -o manager ./cmd/manager

FROM --platform=$TARGETPLATFORM registry.redhat.io/ubi9/ubi-minimal-pqc:latest

WORKDIR /

COPY --from=builder /app/manager /manager

RUN chmod +x /manager
COPY maas-api/deploy /maas-api/deploy
COPY deployment/base/maas-api /deployment/base/maas-api
COPY deployment/base/maas-controller/policies /deployment/base/maas-controller/policies
COPY deployment/base/payload-processing /deployment/base/payload-processing
COPY deployment/components /deployment/components
RUN chmod -R g=u /maas-api /deployment

# Use a non-root user (OpenShift will assign random UID)
USER 1001

ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-maas-controller-rhel9" \
      name="rhoai/odh-maas-controller-rhel9" \
      description="odh-maas-controller" \
      summary="odh-maas-controller" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-maas-controller" \
      io.k8s.description="odh-maas-controller" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
