site_name: ODH Model-as-a-Service Documentation
site_url: https://opendatahub-io.github.io/maas-billing
repo_url: https://github.com/opendatahub-io/maas-billing
repo_name: opendatahub-io/maas-billing

# Set the docs directory to the content subdirectory
docs_dir: content

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.boost
  palette:
    - scheme: slate
      primary: white
      accent: blue
      background: '#0d1117'
      surface: '#161b22'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: blue
      background: '#ffffff'
      surface: '#f6f8fa'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - search:
      lang: en
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - Quick Start: installation.md
  - User Guide:
    - Installation:
      - Prerequisites: install/prerequisites.md
      - install/odh-setup.md
    - User Guide: user-guide.md
    - Model Access: model-access.md
    - Configuration & Management:
      - Tier Management: tier-management.md
      - Token Management: token-management.md
      - Gateway Setup: gateway-setup.md
    - Advanced Administration:
      - Observability: observability.md
  - Architecture: architecture.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
