apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  name: default-dsc
  namespace: opendatahub
spec:
  components:
    # Core dashboard component for managing notebooks and models
    dashboard:
      managementState: Managed
    
    # Notebook controller for JupyterLab workbenches
    workbenches:
      managementState: Managed
    
    # Model serving with KServe configured for RawDeployment mode
    # This configuration:
    # - Uses RawDeployment mode instead of Knative/Serverless
    # - Enables NVIDIA NIM support for GPU-accelerated inference
    # - Uses headless services for direct pod communication
    # - Integrates with OpenShift's default ingress
    kserve:
      managementState: Managed
      defaultDeploymentMode: RawDeployment  # Direct pod deployments without Knative
      nim:
        managementState: Managed  # Enable NVIDIA NIM (NVIDIA Inference Microservices) support
      rawDeploymentServiceConfig: Headless  # Use headless services for raw deployments
      serving:
        ingressGateway:
          certificate:
            type: OpenshiftDefaultIngress  # Use OpenShift's default ingress certificate
        managementState: Removed  # Disable Knative serving (incompatible with RawDeployment)
        name: knative-serving
    
    # Other components disabled for MaaS-focused deployment
    modelmeshserving:
      managementState: Removed  # Use KServe instead
    
    datasciencepipelines:
      managementState: Removed  # Not needed for MaaS
    
    ray:
      managementState: Removed  # Not needed for MaaS
    
    kueue:
      managementState: Removed  # Not needed for MaaS
    
    modelregistry:
      managementState: Removed  # Not needed for MaaS
    
    trustyai:
      managementState: Removed  # Not needed for MaaS
    
    trainingoperator:
      managementState: Removed  # Not needed for MaaS 