apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: odh-installation

namespace: opendatahub

resources:
  # DSCInitialization must be created before DataScienceCluster
  - dscinitialisation.yaml
  - datasciencecluster.yaml 