name: MaaS API Release

on:
  push:
    tags:
      - 'v*'

permissions:
  actions: read
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: maas-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: maas-api/go.mod
          cache: true
          cache-dependency-path: maas-api/go.sum

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.APP_QUAY_USERNAME }}
          password: ${{ secrets.APP_QUAY_TOKEN }}

      - name: Build and Push image to Quay.io
        run: make build-push-image TAG=${{ github.ref_name }}